config/routes.rb
Rails.application.routes.draw do
  root :to =>'admin/sum_messages#index'
  get "/admin" => "admin/users#index"

  devise_for :users, :controllers => { :sessions => "sessions",:registrations => "registrations",:passwords => "passwords",:confirmations => "confirmations" }

  namespace :admin do

    resources :users do
      collection do
        get "/user_password/:id" => "users#password"
        post "/more_user" => "users#more_user"
        post "/change_password/:id" => "users#change_password"
      end
    end    

    resources :sum_messages do 
      collection do
        post "/more_sum_message" => "sum_messages#more_sum_message"
      end
    end

    resources :documents do
      collection do
        post "/more_document" => "documents#more_document"
      end
    end

  end


  # api
  namespace :api do
    namespace :v1 do

      resources :documents
      
    end
  end
  
end

app/models/sum_message.rb
# coding: utf-8
class SumMessage < ActiveRecord::Base

  validates_presence_of :post_id
  validates_uniqueness_of :post_id
  
  def show_genre
    {1 => "type1", 2 => "type2", 3 => "type3"}[self.genre]
  end

end

app/controllers/admin/sum_messages_controller.rb
# coding: utf-8
class Admin::SumMessagesController < Admin::BaseController

  def index
    
  end

  def more_sum_message
    @search = params[:search][:value] ? params[:search][:value] : ""
    @per_page = params[:per_page] ? params[:per_page] : 10
    page = params[:page] || 1
    start = params[:start].to_i || 0
    length = params[:length] ? params[:length].to_i : 10
    page = (start / length) + 1;
    @per_page = length;
    sum_messages = SumMessage.where([]).paginate(page: page , per_page: @per_page).order("id DESC")
    data = sum_messages.collect { |item| {:id => item.id, :post_id => item.post_id, :impression_count => item.impression_count, :click_count => item.click_count, :comment_count => item.comment_count, :praise_count => item.praise_count, :qq_share_count => item.qq_share_count, :wechat_share_count => item.wechat_share_count, :weibo_share_count => item.weibo_share_count, :genre => item.show_genre} }
    has_more = (sum_messages.length == 0 ? false : true)
    all_count = sum_messages.count
    draw = params[:draw].to_i + 1
    render :json => {:draw => draw, :has_more => has_more, :start => start, :recordsTotal => all_count, :recordsFiltered => all_count, :data => data }
  end   

  def show
    time = Time.now
    @sum_message = SumMessage.find(params[:id])
    @time_type = params[:time_type].to_i || 1#1小时，2天

    if @time_type == 1#小时
      @start_time = params[:start_time] || (time - 24*60*60)
      @end_time = params[:end_time] || time
      @messages = HourMessage.where(["post_id = ? and operation_time >= ? and operation_time <= ?", @sum_message.post_id, @start_time, @end_time]).order("operation_time ASC")
    else#天
      @start_time = params[:start_time] || (time - 7*24*60*60)
      @end_time = params[:end_time] || time
      @messages = DayMessage.where(["post_id = ? and operation_time >= ? and operation_time <= ?", @sum_message.post_id, @start_time, @end_time]).order("operation_time ASC")
    end

    p @messages
  end


  private

  def sum_message_params
    params.require(:sum_message).permit(:post_id, :impression_count, :click_count, :comment_count, :praise_count, :qq_share, :wechat_share, :weibo_share, :genre)
  end
end

app/views/admin/sum_messages/index.html.erb
<!-- BEGIN PAGE HEAD -->
<div class="page-head">
  <div class="container">
    <!-- BEGIN PAGE TITLE -->
    <div class="page-title">
      <h1>数据统计</h1>
    </div>
    <!-- END PAGE TITLE -->
  </div>
</div>
<!-- END PAGE HEAD -->
<!-- BEGIN PAGE CONTENT -->
<div class="page-content">
  <div class="container">
    <!-- BEGIN PAGE BREADCRUMB -->
    <ul class="page-breadcrumb breadcrumb">
      <li class="active">统计列表页</li>
    </ul>
    <!-- END PAGE BREADCRUMB -->

    <!-- BEGIN PAGE CONTENT INNER -->
      <div class="row">
        <div class="col-md-12">
          <!-- Begin: life time stats -->
          <div class="portlet light">
            <div class="portlet-title">
              <div class="caption">
                <i class="fa fa-gift font-green-sharp"></i>
                <span class="caption-subject font-green-sharp bold uppercase">统计列表</span>
                <span class="caption-helper">管理统计</span>
              </div>
              <div class="actions">
              </div> 
            </div>

            <div class="portlet-body">
              <div class="table-container">
                <table class="com-datatable-ajax table table-striped table-bordered table-hover" data-url="<%= more_sum_message_admin_sum_messages_path %>">
                  <thead>
                    <tr role="row" class="heading">
                        <th class="table-checkbox" width="6%">
                          <input type="checkbox" class="group-checkable" />
                        </th>
                        <th>文章ID</th>
                        <th>曝光量</th>
                        <th>点击量</th>
                        <th>评论量</th>
                        <th>赞数</th>
                        <th>QQ分享</th>
                        <th>微信分享</th>
                        <th>微博分享</th>
                        <th>文章类型</th>
                        <th width="12%">操作</th>
                    </tr>
                  </thead>
                  <tbody>
                  </tbody>
                </table>
              </div>
            </div>
          </div>
          <!-- End: life time stats -->
        </div>
      </div>
      <!-- END PAGE CONTENT INNER -->
  </div>
</div>
<!-- END PAGE CONTENT -->

app/views/admin/sum_messages/show.html.erb
<!-- BEGIN PAGE CONTENT -->
<div class="page-content">
    <div class="container">
        <%= render :partial => 'components/admin/page-breadcrumb/index' %>

        <!-- BEGIN PAGE CONTENT INNER -->
        <div class="row">
            <div class="col-md-12">
                <!-- Begin: life time stats -->
                <!-- BEGIN VALIDATION STATES-->
                <div class="portlet light">
                    <div class="portlet-title">
                        <div class="caption">
                          <i class="fa fa-cogs font-green-sharp"></i>
                          <span class="caption-subject font-green-sharp bold uppercase"></span>
                        </div>
                    </div>

                    <div class="portlet-body">
                        <div class="portlet light">
                            <div class="portlet-title">
                                <div class="caption">
                                  <i class="fa fa-cogs font-green-sharp"></i>
                                  <span class="caption-subject font-green-sharp bold uppercase"></span>
                                </div>
                            </div>

                            <div class="portlet-body">
                                <div class="com-line-chart" data-origin-data='{
                                    "title": "分享统计",
                                    "xAxis": "周一,周二,周三,周四,周五,周六,周日",
                                    "series": [{
                                        "name": "微博分享量",
                                        "data": "1,-2,2,5,3,2,0"
                                    },{
                                        "name": "微信分享量",
                                        "data": "1,-2,20,125,3,2,30"
                                    }]}'>
                                </div>
                            </div>
                        </div>
                    </div>
                </div>
                <!-- End: life time stats -->
            </div>
        </div>
        <!-- END PAGE CONTENT INNER -->
    </div>
</div>
<!-- END PAGE CONTENT