config/routes.rb
Rails.application.routes.draw do
  root :to =>'admin/sum_messages#index'
  get "/admin" => "admin/users#index"

  devise_for :users, :controllers => { :sessions => "sessions",:registrations => "registrations",:passwords => "passwords",:confirmations => "confirmations" }

  namespace :admin do

    resources :users do
      collection do
        get "/user_password/:id" => "users#password"
        post "/more_user" => "users#more_user"
        post "/change_password/:id" => "users#change_password"
      end
    end    

    resources :sum_messages do 
      collection do
        post "/more_sum_message" => "sum_messages#more_sum_message"
      end
    end

    resources :documents do
      collection do
        post "/more_document" => "documents#more_document"
      end
    end

  end


  # api
  namespace :api do
    namespace :v1 do

      resources :documents
      
    end
  end
  
end

app/models/document.rb
# coding: utf-8
class Document < ActiveRecord::Base

  # 生成一层文件夹
  Paperclip.interpolates :day do |attachment, style|
    attachment.instance.created_at.strftime("%Y%m%d")
  end

  Paperclip.interpolates :hour do |attachment, style|
    attachment.instance.created_at.strftime("%H")
  end

  has_attached_file :file,
    default_url: "/file/missing_file.csv",
    url: "/system/:class/:attachment/:day/:hour/:id.:extension",
    whiny: false
    validates_attachment_content_type :file, content_type: /text/


  def show_status
    {1 => "未计算", 2 => "计算完", 3 => "文件错误"}[self.status]
  end

end

app/controllers/admin/documents_controller.rb
# coding: utf-8
class Admin::DocumentsController < Admin::BaseController

  def index
  end

  def more_document
    @search = params[:search][:value] ? params[:search][:value] : ""
    @per_page = params[:per_page] ? params[:per_page] : 10
    page = params[:page] || 1
    start = params[:start].to_i || 0
    length = params[:length] ? params[:length].to_i : 10
    page = (start / length) + 1;
    @per_page = length;
    documents = Document.where(["file_file_name like ? and state = ?", "%%#{@search}%%", true]).paginate(page: page , per_page: @per_page).order("id DESC")
    data = documents.collect { |item| {:id => item.id, :file_name => item.file_file_name, :file_size => item.file_file_size, :created_at => item.created_at.strftime('%Y-%m-%d %H:%M:%S'), :status => item.show_status } }
    has_more = (documents.length == 0 ? false : true)
    all_count = documents.count
    draw = params[:draw].to_i + 1
    render :json => {:draw => draw, :has_more => has_more, :start => start, :recordsTotal => all_count, :recordsFiltered => all_count, :data => data }
  end 


  def new
    @document = Document.new
  end


  def edit
    @document = Document.find(params[:id])
  end


  def create
    @document = Document.new(document_params)
    if @document.save
      $redis.lpush("documents", @document.id)
      redirect_to admin_documents_url, notice: '新建成功！'
    else
      render :new
    end
  end


  def update
    @document = Document.find(params[:id])
    if @document.update(document_params)
      redirect_to admin_documents_url, notice: '编辑成功！'
    else
      render :edit
    end
  end 


  def destroy
    @document = Document.find(params[:id])
    @document.destroy
    redirect_to admin_documents_url
  end
  

  private

  def document_params
    params.require(:document).permit(:file, :status, :state)
  end
end

app/controllers/api/v1/documents_controller.rb
# coding: utf-8
class Api::V1::DocumentsController < Admin::BaseController

	def create
		@document = Document.new(document_params)

		if @document.save
			$redis.lpush("documents", @document.id)
			render json: {state: true}
		else
			render json: {state: false}
		end
	end


	private

	def document_params
		params.require(:document).permit(:file, :status, :state)
	end
	
end

app/views/admin/documents/_form.html.erb
<!-- BEGIN VALIDATION STATES-->
<div class="portlet light">
  <div class="portlet-title">
    <div class="caption">
      <i class="fa fa-cogs font-green-sharp"></i>
      <span class="caption-subject font-green-sharp bold uppercase">表单</span>
    </div>
  </div>
  <div class="portlet-body form">
    <!-- BEGIN FORM-->
    <%= form_for([:admin, @document], :html => {:class => 'form-horizontal clearfix activity-form-validate', :role => 'form' , :enctype => 'multipart/form-data'}) do |f| %>
    <div class="form-body">

      <div class="form-group fileupload">
        <%= f.label(:file, "文件", :class => "col-md-3 control-label") %>
        <div class="col-md-4">
          <% 
            file_name = @document.file.to_s 
            file_name = file_name.include?('missing') ? '' : file_name.split('?')[0]
          %>
          <%= f.file_field(:file, :class => "dropify", :"data-default-file" => "#{file_name}" ) %>
        </div>
      </div>

    </div>
    <div class="form-actions">
        <div class="row">
            <div class="col-md-offset-3 col-md-9">
                <%= link_to '返回', admin_documents_path, :class => 'btn btn-default' %>
                <% if action_name == 'new' %>
                <button type="submit" class="btn green">保存</button>
                <% else %>
                <button type="submit" class="btn green">更新</button>
                <% end %>
            </div>
        </div>
    </div>
    <% end %>
    <!-- END FORM-->
  </div>
</div>
<!-- END VALIDATION STATES-->

app/views/admin/documents/edit.html.erb
<!-- BEGIN PAGE CONTENT -->
<div class="page-content">
    <div class="container">
        <%= render :partial => 'components/admin/page-breadcrumb/index' %>

        <!-- BEGIN PAGE CONTENT INNER -->
        <div class="row">
            <div class="col-md-12">
                <!-- Begin: life time stats -->
                <%= render :partial => 'form' %>
                <!-- End: life time stats -->
            </div>
        </div>
        <!-- END PAGE CONTENT INNER -->
    </div>
</div>
<!-- END PAGE CONTENT -->

app/views/admin/documents/index.html.erb
<!-- BEGIN PAGE HEAD -->
<div class="page-head">
  <div class="container">
    <!-- BEGIN PAGE TITLE -->
    <div class="page-title">
      <h1>文件列表</h1>
    </div>
    <!-- END PAGE TITLE -->
  </div>
</div>
<!-- END PAGE HEAD -->
<!-- BEGIN PAGE CONTENT -->
<div class="page-content">
  <div class="container">
    <!-- BEGIN PAGE BREADCRUMB -->
    <ul class="page-breadcrumb breadcrumb">
      <li class="active">文件列表</li>
    </ul>
    <!-- END PAGE BREADCRUMB -->
    <!-- BEGIN PAGE CONTENT INNER -->
      <div class="row">
        <div class="col-md-12">
          <!-- Begin: life time stats -->
          <div class="portlet light">
            <div class="portlet-title">
              <div class="caption">
                <i class="fa fa-gift font-green-sharp"></i>
                <span class="caption-subject font-green-sharp bold uppercase">文件列表</span>
                <span class="caption-helper">管理文件</span>
              </div>
              <div class="actions">
                <a href="<%= new_admin_document_path %>" class="btn btn-default btn-circle">
                  <i class="fa fa-plus"></i>
                  <span class="hidden-480"> 新建文件</span>
                </a>
              </div>              
            </div>
            <div class="portlet-body">
              <div class="table-container">
                <table class="com-datatable-ajax table table-striped table-bordered table-hover" data-url="<%= more_document_admin_documents_path %>">
                  <thead>
                    <tr role="row" class="heading">
                      <th class="table-checkbox" width="6%">
                        <input type="checkbox" class="group-checkable" />
                      </th>
                      <th>文件名称</th>
                      <th>文件大小</th>
                      <th>文件上传日期</th>
                      <th>处理状态</th>
                      <th width="12%">操作</th>
                    </tr>
                  </thead>
                  <tbody>
                  </tbody>
                </table>
              </div>
            </div>
          </div>
          <!-- End: life time stats -->
        </div>
      </div>
      <!-- END PAGE CONTENT INNER -->
  </div>
</div>
<!-- END PAGE CONTENT

app/views/admin/documents/new.html.erb
<!-- BEGIN PAGE CONTENT -->
<div class="page-content">
    <div class="container">
        <%= render :partial => 'components/admin/page-breadcrumb/index' %>

        <!-- BEGIN PAGE CONTENT INNER -->
        <div class="row">
            <div class="col-md-12">
                <!-- Begin: life time stats -->
                <%= render :partial => 'form' %>
                <!-- End: life time stats -->
            </div>
        </div>
        <!-- END PAGE CONTENT INNER -->
    </div>
</div>
<!-- END PAGE CONTENT -->