config/routes.rb
Rails.application.routes.draw do
  root :to =>'admin/sum_messages#index'
  get "/admin" => "admin/users#index"

  devise_for :users, :controllers => { :sessions => "sessions",:registrations => "registrations",:passwords => "passwords",:confirmations => "confirmations" }

  namespace :admin do

    resources :users do
      collection do
        get "/user_password/:id" => "users#password"
        post "/more_user" => "users#more_user"
        post "/change_password/:id" => "users#change_password"
      end
    end    

    resources :sum_messages do 
      collection do
        post "/more_sum_message" => "sum_messages#more_sum_message"
      end
    end

    resources :documents do
      collection do
        post "/more_document" => "documents#more_document"
      end
    end

  end


  # api
  namespace :api do
    namespace :v1 do

      resources :documents
      
    end
  end
  
end

app/models/user.rb
# coding: utf-8
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable

  has_attached_file :face,
    styles: { medium: "180x180#", small: "80x80#" },
    default_url: "/img/missing_face.png",
    url: "/system/:class/:attachment/:id/:style/:id.:extension",
    whiny: false
    validates_attachment_content_type :face, content_type: /\Aimage\/.*\Z/

  def show_genre
    {1 => "超级管理员", 2 => "管理员", 3 => "普通用户"}[self.genre]
  end

end

app/controllers/admin/users_controller.rb
# coding: utf-8
class Admin::UsersController < Admin::BaseController

  before_action :find_user, only: [:edit, :update, :password, :change_password, :destroy]

  def index
  end

  def more_user
    @search = params[:search][:value] ? params[:search][:value] : ""
    @per_page = params[:per_page] ? params[:per_page] : 10
    page = params[:page] || 1
    start = params[:start].to_i || 0
    length = params[:length] ? params[:length].to_i : 10
    page = (start / length) + 1;
    @per_page = length;
    users = User.where(["username like ?", "%%#{@search}%%"]).paginate(page: page , per_page: @per_page).order("id DESC")
    data = users.collect { |item| {:id => item.id, :username => item.username, :email => item.email, :genre => item.show_genre} }
    has_more = (users.length == 0 ? false : true)
    all_count = users.count
    draw = params[:draw].to_i + 1
    render :json => {:draw => draw, :has_more => has_more, :start => start, :recordsTotal => all_count, :recordsFiltered => all_count, :data => data }
  end

  def new
    @user = User.new
  end

  def edit
    
  end

  def create
    @user = User.new(user_params)
    if @user.save
      redirect_to admin_users_url, notice: '新建成功！'
    else
      render :new
    end
  end

  def update
    get_user_params = user_params
    get_user_params.except!(:password, :password_confirmation) if user_params[:password].blank? && user_params[:password_confirmation].blank?
    if @user.update(get_user_params)
      redirect_to admin_users_url, notice: '更新成功！'
    else
      render :edit
    end
  end

  def password
    render json: @user
  end

  def change_password
    if @user.update(user_params)
      redirect_to "/admin/users"
    else
      redirect_to "/admin/users"
    end
  end

  def destroy
    @user.destroy
    redirect_to admin_users_url
  end

  private

  def find_user
    @user = User.find(params[:id])
  end

  
  def user_params
    params.require(:user).permit(:username, :email, :face, :genre, :password, :password_confirmation)
  end

end

app/helpers/admin/users_helper.rb
module Admin::UsersHelper
end

app/views/admin/users/_form.html.erb
<!-- BEGIN VALIDATION STATES-->
<div class="portlet light">
  <div class="portlet-title">
    <div class="caption">
      <i class="fa fa-cogs font-green-sharp"></i>
      <span class="caption-subject font-green-sharp bold uppercase">表单</span>
    </div>
  </div>
  <div class="portlet-body form">
    <!-- BEGIN FORM-->
    <%= form_for([:admin, @user], :html => {:class => 'form-horizontal clearfix user-form-validate', :role => 'form'}) do |f| %>
    <div class="form-body">
    <div class="form-group">
      <%= f.label(:username, '用户名', :class => "col-md-2 control-label") %>
      <div class="col-md-4">
        <%= f.text_field(:username, :placeholder => '用户名', :class => 'form-control') %>
      </div>
    </div>
    <div class="form-group">
      <%= f.label(:email, '邮箱', :class => "col-md-2 control-label") %>
      <div class="col-md-4">
        <%= f.text_field(:email, :placeholder => '邮箱', :class => 'form-control') %>
      </div>
    </div>
    <div class="form-group">
      <%= f.label(:genre, '用户类型', :class => "col-md-2 control-label") %>
      <div class="col-md-4">
        <%= f.select(:genre, [['普通用户', 3], ['管理员', 2], ['超级管理员', 1]], {}, :class => 'form-control') %>
      </div>
    </div>
    <div class="form-group">
      <%= f.label(:password, '密码', class: 'col-md-2 control-label') %>
      <div class="col-md-4">
        <%= f.password_field :password, class: 'form-control' %>
      </div>
    </div>
    <div class="form-group">
      <%= f.label(:password_confirmation, '确认密码', class: 'col-md-2 control-label') %>
      <div class="col-md-4">
        <%= f.password_field :password_confirmation, class: 'form-control' %>
      </div>
    </div>
    <div class="form-group">
      <%= f.label(:face, '头像', :class => "col-md-2 control-label") %>
      <div class="col-md-4">
        <div class="fileinput fileinput-new" data-provides="fileinput">
          <div class="fileinput-new thumbnail" style="width: 200px; height: 150px;">
            <img src="<%= @user.face.url(:small) %>" alt=""/>
          </div>
          <div class="fileinput-preview fileinput-exists thumbnail" style="max-width: 200px; max-height: 150px;">
          </div>
          <div>
            <span class="btn default btn-file">
              <span class="fileinput-new">选择图片(80x80)</span>
              <span class="fileinput-exists">修改</span>
              <%= f.file_field(:face, :accept => "image/*") %>
            </span>
            <a href="#" class="btn red fileinput-exists" data-dismiss="fileinput">移除</a>
          </div>
        </div>
      </div>
    </div>
    </div>
    <div class="form-actions">
        <div class="row">
            <div class="col-md-offset-3 col-md-9">
                <%= link_to '返回', admin_users_path, :class => 'btn btn-default' %>
                <% if action_name == 'new' %>
                <button type="submit" class="btn green">保存</button>
                <% else %>
                <button type="submit" class="btn green">更新</button>
                <% end %>
            </div>
        </div>
    </div>
    <% end %>
    <!-- END FORM-->
  </div>
</div>
<!-- END VALIDATION STATES-->

app/views/admin/users/edit.html.erb
<!-- BEGIN PAGE CONTENT -->
<div class="page-content">
    <div class="container">
        <%= render :partial => 'components/admin/page-breadcrumb/index' %>

        <!-- BEGIN PAGE CONTENT INNER -->
        <div class="row">
            <div class="col-md-12">
                <!-- Begin: life time stats -->
                <%= render :partial => 'form' %>
                <!-- End: life time stats -->
            </div>
        </div>
        <!-- END PAGE CONTENT INNER -->
    </div>
</div>
<!-- END PAGE CONTENT -->

app/views/admin/users/index.html.erb
<!-- BEGIN PAGE HEAD -->
<div class="page-head">
  <div class="container">
    <!-- BEGIN PAGE TITLE -->
    <div class="page-title">
      <h1>用户列表 <small>statistics & reports</small></h1>
    </div>
    <!-- END PAGE TITLE -->
  </div>
</div>
<!-- END PAGE HEAD -->
<!-- BEGIN PAGE CONTENT -->
<div class="page-content">
  <div class="container">
    <!-- BEGIN PAGE BREADCRUMB -->
    <ul class="page-breadcrumb breadcrumb">
      <li class="active">用户列表页</li>
    </ul>
    <!-- END PAGE BREADCRUMB -->
    <!-- BEGIN PAGE CONTENT INNER -->
      <div class="row">
        <div class="col-md-12">
          <!-- Begin: life time stats -->
          <div class="portlet light">
            <div class="portlet-title">
              <div class="caption">
                <i class="fa fa-gift font-green-sharp"></i>
                <span class="caption-subject font-green-sharp bold uppercase">用户列表</span>
                <span class="caption-helper">管理用户</span>
              </div>
              <div class="actions">
                <a href="<%= new_admin_user_path %>" class="btn btn-default btn-circle">
                  <i class="fa fa-plus"></i>
                  <span class="hidden-480"> 新建用户</span>
                </a>
              </div>
            </div>
            <div class="portlet-body">
              <div class="table-container">
                <table class="com-datatable-ajax table table-striped table-bordered table-hover" data-url="<%= more_user_admin_users_path %>">
                  <thead>
                    <tr role="row" class="heading">
                        <th class="table-checkbox" width="6%">
                            <input type="checkbox" class="group-checkable" />
                        </th>
                        <th>用户名</th>
                        <th>邮箱</th>
                        <th width="8%">用户类型</th>
                        <th width="12%">操作</th>
                    </tr>
                  </thead>
                  <tbody>
                  </tbody>
                </table>
              </div>
            </div>
          </div>
          <!-- End: life time stats -->
        </div>
      </div>
      <!-- END PAGE CONTENT INNER -->
  </div>
</div>
<!-- END PAGE CONTENT -->

app/views/admin/users/new.html.erb
<!-- BEGIN PAGE CONTENT -->
<div class="page-content">
    <div class="container">
        <%= render :partial => 'components/admin/page-breadcrumb/index' %>

        <!-- BEGIN PAGE CONTENT INNER -->
        <div class="row">
            <div class="col-md-12">
                <!-- Begin: life time stats -->
                <%= render :partial => 'form' %>
                <!-- End: life time stats -->
            </div>
        </div>
        <!-- END PAGE CONTENT INNER -->
    </div>
</div>
<!-- END PAGE CONTENT -->